[
    uuid(12345678-1234-1234-1234-1234567890AB),
    version(1.0),
    pointer_default(unique)
]
interface TrayRpc
{
    boolean StopService([in] handle_t hBinding);

    long GetCurrentUser(
        [in] handle_t hBinding,
        [out] boolean* authenticated,
        [in] unsigned long usernameCapacity,
        [out, string, size_is(usernameCapacity)] wchar_t* username
    );

    long Login(
        [in] handle_t hBinding,
        [in, string] const wchar_t* username,
        [in, string] const wchar_t* password
    );

    long Logout([in] handle_t hBinding);

    long GetLicenseInfo(
        [in] handle_t hBinding,
        [out] boolean* licensed,
        [out] hyper* expiresUnix
    );

    long GetAntivirusStatus(
        [in] handle_t hBinding,
        [out] boolean* running
    );

    long ActivateProduct(
        [in] handle_t hBinding,
        [in, string] const wchar_t* activationCode
    );
}
